[package]
name = "cargo-about"
version = "0.2.2"
description = "Cargo plugin for generating a listing of all of the crates and the the terms under which they are licensed"
authors = ["Embark <opensource@embark-studios.com>", "Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"
repository = "https://github.com/EmbarkStudios/cargo-about"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/cargo-about"
homepage = "https://github.com/EmbarkStudios/cargo-about"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo", "license", "spdx"]
exclude = [
  "media/"
]

[badges]
maintenance = { status = "actively-developed" }

[[bin]]
name = "cargo-about"
path = "src/cargo-about/main.rs"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.31"
askalono = "0.4.1"
chrono = "0.4.10"
fern = "0.6.0"
handlebars = { version = "3.5.0", features = ["dir_source"] }
ignore = "0.4.11"
krates = "0.3.0"
license = "1.1.0"
log = "0.4.8"
rayon = "1.3.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.47"
smallvec = "1.2.0"
spdx = "0.3.3"
structopt = "0.3.11"
toml = "0.5.6"
rpmalloc = "0.2"
